version: "3.5"
services:
  serverless:
    build: .
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
    container_name: sls-recon
    env_file:
      - .env.docker
    logging:
      driver: "json-file"
