# NOTE: update this with your service name
service: YOUR_SERVICE_NAME

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-mocha-plugin

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  serverless-offline:
    port: 3000
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(./.env.yml):REGION}
  environment: ${file(./.env.yml)}

functions:
  hello:
    handler: handlers/hello.world
    events:
      - http:
          path: hello
          method: get
          cors: true
