# NOTE: update this with your service name
service: sls-recon

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  serverless-offline:
    port: 3000
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(./.env.yml):REGION}
  environment: ${file(./.env.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:ListStreams
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: ${file(./.env.yml):KINESIS_ARN}

functions:
  reply:
    handler: handlers/app.reply
    events:
      - stream:
          type: kinesis
          arn: ${file(./.env.yml):KINESIS_ARN}
          startingPosition: LATEST
